# Links to be made for tools and scripts
links:
  tracking_tools: auto
  modules: tracking_tools/lhcmask
  tools: tracking_tools/lhctoolkit
  errors: tracking_tools/lhcerrors
  optics_repository: tracking_tools/hllhc14

# Optics file
optics_file: optics_repository/round/opt_round_150_1500_thin.madx
# Optics version
optics_version: '1.4'

# Beam parameters
beam_energy_tot: 7000           # [GeV]

# Verbose flag for MAD-X parts
verbose_mad_parts: true

# Enable machine imperfections
enable_imperfections: true

# Enable knob synthesis (for coupling correction, if no imperfections)
enable_knob_synthesis: true

# Parameters for machine imperfections
pars_for_imperfections:
  par_myseed: 1
  par_correct_for_D2: 0
  par_correct_for_MCBX: 0
  par_on_errors_LHC: 1
  par_off_errors_Q4_inIP15: 0
  par_off_errors_Q5_inIP15: 0
  par_on_errors_MBH: 1
  par_on_errors_Q4: 1
  par_on_errors_D2: 1
  par_on_errors_D1: 1
  par_on_errors_IT: 1
  par_on_errors_MCBRD: 0
  par_on_errors_MCBXF: 0
  par_on_errors_NLC: 0
  par_write_errortable: 1
