knob_settings:

  # Orbit knobs
  on_x1: 250            # [urad]
  on_sep1: 0            # [mm]
  on_x2: -170           # [urad]
  on_sep2: 0.138        # [mm]
  on_x5: 250            # [urad]
  on_sep5: 0            # [mm]
  on_x8: -250           # [urad]
  on_sep8: -0.043       # [mm]
  on_a1: 0              # [urad]
  on_o1: 0              # [mm]
  on_a2: 0              # [urad]
  on_o2: 0              # [mm]
  on_a5: 0              # [urad]
  on_o5: 0              # [mm]
  on_a8: 0              # [urad]
  on_o8: 0              # [mm]
  on_disp: 1            # Value to choose could be optics-dependent

  # Crab cavities
  on_crab1: -190        # [urad]
  on_crab5: -190        # [urad]

  # Magnets of the experiments
  on_alice_normalized: 1
  on_lhcb_normalized: 1
  on_sol_atlas: 0
  on_sol_cms: 0
  on_sol_alice: 0

  # RF voltage and phases
  vrf400:       16.0            # [MV]
  lagrf400.b1:   0.5            # [rad]
  lagrf400.b2:   0.             # [rad]

  # Octupoles
  i_oct_b1:     -235            # [A]
  i_oct_b1:     -235            # [A]

# Tunes and chromaticities
qx: 62.31
qy: 60.32
dqx: 5
dqy: 5

knob_names:

  lhcb1:
    q_knob_1: kqtf.b1
    q_knob_2: kqtd.b1
    dq_knob_1: ksf.b1
    dq_knob_2: ksd.b1
    c_minus_knob_1: c_minus_re_b1
    c_minus_knob_2: c_minus_im_b1

  lhcb2:
    q_knob_1: kqtf.b2
    q_knob_2: kqtd.b2
    dq_knob_1: ksf.b2
    dq_knob_2: ksd.b2
    c_minus_knob_1: c_minus_re_b2
    c_minus_knob_2: c_minus_im_b2